name: lint

on: [push, pull_request]

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install python packages
        run: pip install -r requirements.txt
      - name: Check format with black
        run: python -m black . --check